
export const skillsOptions = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Scala',
  'R',
  'MATLAB',
  'Perl',
  'Haskell',
  'Elixir',
  'Clojure',
  'Dart',

  // Web Technologies
  'HTML',
  'CSS',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Express.js',
  'Next.js',
  'Nuxt.js',
  'Svelte',
  'Ember.js',
  'Backbone.js',
  'jQuery',
  'Bootstrap',
  'Tailwind CSS',
  'Sass',
  'Less',
  'Webpack',
  'Vite',
  'Parcel',
  'Babel',
  'ESLint',
  'Prettier',

  // Backend & Databases
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'Laravel',
  'Ruby on Rails',
  'ASP.NET',
  'Express.js',
  'Koa.js',
  'Hapi.js',
  'Fastify',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'SQL Server',
  'Firebase',
  'Supabase',
  'GraphQL',
  'REST API',

  // Cloud & DevOps
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitLab CI/CD',
  'GitHub Actions',
  'Travis CI',
  'CircleCI',
  'Terraform',
  'Ansible',
  'Chef',
  'Puppet',
  'Vagrant',
  'Vagrant',
  'Nginx',
  'Apache',
  'Linux',
  'Ubuntu',
  'CentOS',
  'Red Hat',

  // Mobile Development
  'React Native',
  'Flutter',
  'Ionic',
  'Xamarin',
  'NativeScript',
  'Cordova',
  'PhoneGap',
  'iOS Development',
  'Android Development',
  'SwiftUI',
  'Jetpack Compose',

  // Data Science & AI
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'Plotly',
  'Jupyter',
  'Data Analysis',
  'Data Visualization',
  'Natural Language Processing',
  'Computer Vision',
  'OpenCV',
  'NLTK',
  'spaCy',

  // Testing
  'Jest',
  'Mocha',
  'Chai',
  'Cypress',
  'Selenium',
  'Playwright',
  'Puppeteer',
  'JUnit',
  'PyTest',
  'RSpec',
  'PHPUnit',
  'Testing',
  'Unit Testing',
  'Integration Testing',
  'E2E Testing',

  // Version Control & Tools
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'SVN',
  'Mercurial',
  'VS Code',
  'IntelliJ IDEA',
  'Eclipse',
  'Vim',
  'Emacs',
  'Sublime Text',
  'Atom',

  // Design & UI/UX
  'UI/UX Design',
  'Figma',
  'Adobe XD',
  'Sketch',
  'InVision',
  'Framer',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe InDesign',
  'Prototyping',
  'Wireframing',
  'User Research',
  'Usability Testing',

  // Other Technical Skills
  'Agile',
  'Scrum',
  'Kanban',
  'Project Management',
  'Technical Writing',
  'Documentation',
  'Code Review',
  'Pair Programming',
  'TDD',
  'BDD',
  'Microservices',
  'API Design',
  'Performance Optimization',
  'Security',
  'Cryptography',
  'Blockchain',
  'Web3',
  'Solidity',
  'Smart Contracts',
  'IoT',
  'Embedded Systems',
  'Arduino',
  'Raspberry Pi',

  // Soft Skills
  'Leadership',
  'Team Management',
  'Communication',
  'Problem Solving',
  'Critical Thinking',
  'Time Management',
  'Mentoring',
  'Public Speaking',
  'Presentation Skills',
  'Negotiation',
  'Conflict Resolution',
  'Adaptability',
  'Creativity',
  'Innovation',
  'Strategic Thinking',
  'Decision Making',
  'Collaboration',
  'Cross-functional Teams',
  'Remote Work',
  'Virtual Collaboration',
];
